name: 'My First Github Actions'

on: push

jobs:
  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello from First Job
        shell: bash
        run: |
          echo "Hello World"
    
  second_job:
    name: 'Second Job'
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello from First Job
        shell: bash
        run: |
          echo "Hello World"
        
